export interface Apartment {
  id: number;
  url: string;
  cian_id?: string | null;
  price: number;
  price_per_meter?: number | null;
  rooms_count: number;
  bedrooms_count?: number | null;
  total_meters?: number | null;
  living_meters?: number | null;
  kitchen_meters?: number | null;
  floor?: number | null;
  floors_count?: number | null;
  building_type?: string | null;
  building_year?: number | null;
  building_class?: string | null;
  ceiling_height?: number | null;
  region?: string | null;
  city?: string | null;
  district?: string | null;
  microdistrict?: string | null;
  street?: string | null;
  house_number?: string | null;
  building?: string | null;
  litter?: string | null;
  apartment_number?: string | null;
  coordinates?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  underground?: string | null;
  underground_line?: string | null;
  underground_time?: string | null;
  underground_distance?: number | null;
  railway_station?: string | null;
  railway_time?: string | null;
  transport_accessibility?: string | null;
  author?: string | null;
  author_type?: string | null;
  author_id?: string | null;
  author_phone?: string | null;
  author_agency?: string | null;
  author_rating?: number | null;
  author_deals_count?: number | null;
  description?: string | null;
  title?: string | null;
  short_description?: string | null;
  renovation_type?: string | null;
  renovation_year?: number | null;
  condition?: string | null;
  furniture?: string | null;
  appliances?: string | null;
  balcony?: string | null;
  bathroom?: string | null;
  windows?: string | null;
  view?: string | null;
  parking?: string | null;
  elevator?: string | null;
  garbage_chute?: boolean | null;
  utilities_included?: boolean | null;
  utilities_price?: number | null;
  electricity_included?: boolean | null;
  water_included?: boolean | null;
  heating_included?: boolean | null;
  deposit?: number | null;
  commission?: string | null;
  commission_percent?: number | null;
  prepayment?: string | null;
  prepayment_months?: number | null;
  lease_term?: string | null;
  children_allowed?: boolean | null;
  pets_allowed?: boolean | null;
  smoking_allowed?: boolean | null;
  amenities?: string[] | null;
  house_amenities?: string[] | null;
  nearby_objects?: string[] | null;
  is_special?: boolean | null;
  special_label?: string | null;
  is_urgent?: boolean | null;
  is_owner?: boolean | null;
  is_agent?: boolean | null;
  is_builder?: boolean | null;
  published_date?: string | null;
  parsed_date?: string | null;
  last_check_date?: string | null;
  is_active?: boolean | null;
  is_archived?: boolean | null;
  photo_paths?: string | null;
  photo_count?: number | null;
  main_photo?: string | null;
  video_urls?: string | null;
  video_count?: number | null;
  virtual_tour_url?: string | null;
  views_count?: number | null;
  favorites_count?: number | null;
  source?: string | null;
  raw_data?: any | null;
}

export interface PaginatedResponse {
  items: Apartment[];
  total: number;
  page: number;
  pages: number;
  per_page: number;
}

export interface Filters {
  page?: number;
  per_page?: number;
  min_price?: number | string;
  max_price?: number | string;
  rooms?: string;
  district?: string;
  underground?: string;
  min_area?: number | string;
  max_area?: number | string;
  author_type?: string;
  has_photo?: boolean;
  is_owner?: boolean;
  is_agent?: boolean;
  sort_by?: string;
}